### ISSUE TITLE
New BOSEUPDATER.EXE version

### ISSUE THREAD

**Issue by GAlli666** [bosefirmware/ced#20]
Hi could you please patch 7.0x boseupdater version , bose no longer accepts the current patched one

**Comment by ClementVH** [comment]
up !
i could use it too :)

**Comment by changshengdeluoye** [comment]
up!
the new version is 7.0.27.4971

**Comment by dcdcdcl** [comment]
up！Now it can't work and the website shows:
There's a new version of the Bose Updater! The version you're running is out-of-date and won't let you access product updates. Download the newest version so you can get updates for all your Bose products.

**Comment by guicn555** [comment]
Up! It's outdated again.

**Comment by chrisplough** [comment]
Upvote :) 
It's headshakingly-bad that Bose Support won't offer this option and that we need to resort to a hacked updater to simply have headphones that work without constantly rebooting. I'm grateful for your time in helping with this. Thank you.

**Comment by TizDu** [comment]
To follow this discussion since indeed it does not work with 7.2.27 and my mic is not working anymore.
for those who succeeded what firmware version did you select finally?

**Comment by TizDu** [comment]
To follow this discussion since indeed it does not work with Boseupdater 7.2.27 and my mic is not working anymore.
for those who succeeded what firmware version did you select finally?

@bosefirmware Any new version available?

@chrisplough did you succeed to revert to older version than 2.5.1 (which is 'allowed' by Bose)

**Comment by chrisplough** [comment]
> @chrisplough did you succeed to revert to older version than 2.5.5 (which is 'allowed' by Bose)

No - currently using 1.3.1, which is the latest stable release that works well with my headphones.

Side note - just wish I didn't have to use the Bose app to select active Bluetooth sources. Somehow I left it open it the headphones were just updated 1.8.2 (and continually crashing again) - so I'm re-downgrading to 1.3.1 now.

**Comment by TizDu** [comment]
Thanks for the answer.
What procedure did you use to downgrade?

if I understand you used  Proxyman on Mac.
Since I only have a windows machine I will need to look at 'Charles Web Debugging Proxy' if I am correct.

**Comment by plague69** [comment]
EXE is now UPX1 packed which isn't an issue. The issue is string for the lookup URL is not longer hard coded in the latest version 7.0.27. Will take some time to see where it gets the info from. Also Bose has moved some firmwares to AWS S3. Old updater string to replace was "http://worldwide.bose.com/connected_device"

In a nutshell, redirect https://downloads.bose.com/lookup.xml
to goto: https://raw.githubusercontent.com/bosefirmware/ced/master/lookup.xml

**Comment by TizDu** [comment]
Thanks

Forgot to mention that I have a QC35 (not the QC35II)

I succeeded to re-install version 1.0.0 but mic was still not working
I am now trying other versions 1 by 1 in order to find one where my Mic is working again.

I  see versions
1.0.0
1.0.3
1.0.4
1.0.5
1.0.6
1.3.2
1.3.6
1.5.1
2.5.3
2.5.5
3.0.3

**Comment by plague69** [comment]
My QC35 original has been sitting in my drawer since I got the NC700, but I do remember Mic wouldn't work on my computer's Bluetooth for a long time now, it did when I got the headphones, but don't recall when it stopped working so I started running on my internal Mic with software noise cancellation. Samsung S8 always worked with it;'s Mic (Fully updated firmware until Oct 2020 whatever it may be)

You can try:
Power off your product
Wait 30 seconds
Connect your product to a wall outlet using a USB charger
Wait five seconds
Disconnect the USB cable from the headset
Wait one minute
Power on your product

[QuietComfort 35 wireless headphones II -Reset - BOSE](https://www.bose.com/en_us/support/articles/HC2563/productCodes/qc35_ii/article.html)

**Comment by smmadge** [comment]
> EXE is now UPX1 packed which isn't an issue. The issue is string for the lookup URL is not longer hard coded in the latest version 7.0.27. Will take some time to see where it gets the info from. Also Bose has moved some firmwares to AWS S3. Old updater string to replace was "http://worldwide.bose.com/connected_device"
> 
> In a nutshell, redirect https://downloads.bose.com/lookup.xml
> to goto: https://raw.githubusercontent.com/bosefirmware/ced/master/lookup.xml

Also doesn't seem to work. I am using chrome-extension "redirector" to redirect the url. If I manually open a tab and try to connect to https://downloads.bose.com/lookup.xml it redirects me to https://raw.githubusercontent.com/bosefirmware/ced/master/lookup.xml

But after pressing the mentioned key combination it doesn't give me the possibility to flash another firmware version. I can only send some diagnostic information to bose. Do you have any idea how to solve this?

**Comment by TizDu** [comment]
on windows I used 'Charles Web Debugging Proxy' and it worked fine, you can find instructions on how to setup that tool above.

**Comment by smmadge** [comment]
Using Charles Web Debugging Proxy instead of the chrome extension worked fine indeed! Back on good old 1.3.1 again ;-) Thanks!

**Comment by klimelau** [comment]
> Using Charles Web Debugging Proxy instead of the chrome extension worked fine indeed! Back on good old 1.3.1 again ;-) Thanks!

May I ask for screenshots of your Charles mapping settings? I can't seem to get it working properly, the Bose webpage ends up with a pop-up window saying "This didn't work. Restart Bose Updater or refresh browser"

**Comment by smmadge** [comment]
It looks exactly like this: https://github.com/bosefirmware/ced/issues/4#issuecomment-556381149

I used internet explorer/edge on windows 10. Did you import the root certificate (http://chls.pro/ssl) in the correct root ca store (don't let windows choose the certificate store for you since it will pick the wrong one)?

**Comment by gentleben** [comment]
After configuring the Charles Web Debugging Proxy, I could see 1 older firmware version for my Soundlink Mini 2 that I couldn't see before. My SLM2 has a red flashing power light, which should be fixed by reapplying firmware. However, when I select the older version and try to apply that, I get the message "No Dice. There are no available updates for this product.". I guess the proxy redirects aren't enough to trick Bose into re-flashing and thus fixing my broken Soundlink Mini 2? Don't think I'll buy Bose again! :-(

**Comment by lambdastormII** [comment]
Man this is seriously depressing. After fiddling with charles web debugging proxy I'm able to get into advanced mode however I can only see two firmwares one 3.0.3 the other 2.5.5. My unit is the original QC35. How the frick is bose not letting me go below 2.5.5??????? I thought only some QC35 II has this problem.

**Comment by lambdastormII** [comment]
[https://i.imgur.com/DL3rDhm.png](url)

**Comment by arjunbj** [comment]
Any ideas on how to deal with 'no dice' error?
![image](https://user-images.githubusercontent.com/22302475/178931665-34522596-de5b-4b87-afb1-e38a7affb3fd.png)

**Comment by Canawan** [comment]
The bose headphones and speakers still have a lot of errors but no one else is here, it may be too late for me to ask someone how to fix the red white flashing error on my bose quietcomfort earbuds

**Comment by Canawan** [comment]
The bose headphones and speakers still have a lot of errors but no one else is here, it may be too late for me to ask someone how to fix the red white flashing error on my bose quietcomfort earbuds.
